/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include <GLES2/gl2.h>
#include <GLES2/gl2ext.h>
#include <android/log.h>
#include <android/asset_manager.h>
#include <android/asset_manager_jni.h>
#include "glm/glm.hpp"
#include "glm/ext.hpp"
/* Header for class com_wang_hellounity_openglcsdndemo_GLSurfaceImpl */

#ifndef _Included_com_wang_hellounity_openglcsdndemo_GLSurfaceImpl
#define _Included_com_wang_hellounity_openglcsdndemo_GLSurfaceImpl
#ifdef __cplusplus
extern "C" {
#endif

GLuint vbo;
GLuint simple_program;
GLint MLocation,VLocation,PLocation,positionLocation,texcoordLocation,mainTextureLocation;
GLuint mainTexture;

glm::mat4 identityMatrix;
glm::mat4 projectionMatrix;

const char *vsPath="";

AAssetManager* sAssetManager = nullptr;

#define info(...) __android_log_print(ANDROID_LOG_INFO,"GLSurfaceImpl", __VA_ARGS__)

char * LoadFileContent(const char *path);

GLuint CompileShader(GLenum shaderType,const char* code);

GLuint CreateProgram(const char* vsCode,const char* fsCode);

GLuint CreateTextureWithBMPData(unsigned char *imageData,int width,int height);

GLuint CreateTexture(int size);

unsigned char* DecodeBMP(char* path,int&width,int&height);

JNIEXPORT void JNICALL Java_com_wang_hellounity_openglcsdndemo_GLSurfaceImpl_initAsset
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_wang_hellounity_openglcsdndemo_GLSurfaceImpl
 * Method:    onSurfaceCreated
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_wang_hellounity_openglcsdndemo_GLSurfaceImpl_onSurfaceCreated
  (JNIEnv *, jobject);

/*
 * Class:     com_wang_hellounity_openglcsdndemo_GLSurfaceImpl
 * Method:    onSurfaceChanged
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_com_wang_hellounity_openglcsdndemo_GLSurfaceImpl_onSurfaceChanged
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_wang_hellounity_openglcsdndemo_GLSurfaceImpl
 * Method:    onDrawFrame
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_wang_hellounity_openglcsdndemo_GLSurfaceImpl_onDrawFrame
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
